name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  release:
    uses: sxzz/workflows/.github/workflows/release.yml@v1
    with:
      publish: true
      build: pnpm build

    permissions:
      contents: write
      id-token: write
